### ISSUE TITLE
Extensions can't be installed from the marketplace

### ISSUE THREAD

**Issue by VladimirMikulic** [noGreg/scribdStrip#2]
Hi!
I like the idea of your extension, but I am unable to install it.
Here is the error:

![Screenshot_20200320_221734](https://user-images.githubusercontent.com/35997844/77207134-e4b93c80-6af8-11ea-9d51-fade00cd37be.png)

Let me know if I could help further. Thanks.

**Comment by noGreg** [comment]
I need to know which instalation process did you follow, and what version of chrome are you using. 
And thanks for reporting 👍

**Comment by VladimirMikulic** [comment]
Of course! Sorry about that.
There is no special installation process, I just went to marketplace, searched for an extension and clicked "Add to chrome".
Chrome version: 80.0.3987.149

**Comment by noGreg** [comment]
Everything sound really good.

And, finally, did you retry the install after reload the marketplace page or relaunch the chrome app?

**Anyway I have to recognize that the image file extension is on uppercase "sLogo.PNG" instead of "sLogo.png" and it's bugging the process particularly on your device.**

I'm already uploading a new version to patch this.

A lot of thanks @VladimirMikulic

**Comment by VladimirMikulic** [comment]
@noGreg it still doesn't work. The same pop-up appears.

**Comment by noGreg** [comment]
@VladimirMikulic sorry, but the changes may take days to review. Just wait or try to install it on some other device
